// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Category struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Order struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	TotalAmount string        `json:"total_amount"`
	Status      string        `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type OrderItem struct {
	ID               int32         `json:"id"`
	OrderID          sql.NullInt32 `json:"order_id"`
	ProductVariantID sql.NullInt32 `json:"product_variant_id"`
	Quantity         int32         `json:"quantity"`
	Price            string        `json:"price"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type PasswordReset struct {
	ID         int32         `json:"id"`
	UserID     sql.NullInt32 `json:"user_id"`
	ResetToken string        `json:"reset_token"`
	CreatedAt  time.Time     `json:"created_at"`
	ExpiresAt  time.Time     `json:"expires_at"`
}

type Product struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	CategoryID  sql.NullInt32  `json:"category_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProductVariant struct {
	ID        int32         `json:"id"`
	ProductID sql.NullInt32 `json:"product_id"`
	Color     string        `json:"color"`
	Size      string        `json:"size"`
	Stock     int32         `json:"stock"`
	Price     string        `json:"price"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Review struct {
	ID        int32          `json:"id"`
	ProductID sql.NullInt32  `json:"product_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Sale struct {
	ID         int32          `json:"id"`
	Month      sql.NullInt32  `json:"month"`
	Year       sql.NullInt32  `json:"year"`
	TotalSales sql.NullString `json:"total_sales"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type User struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Email     string          `json:"email"`
	Password  string          `json:"password"`
	Role      string          `json:"role"`
	Addresses json.RawMessage `json:"addresses"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Wishlist struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	ProductID sql.NullInt32 `json:"product_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
