// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: review.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (product_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, user_id, rating, comment, created_at, updated_at
`

type CreateReviewParams struct {
	ProductID sql.NullInt32  `json:"product_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getReviewById = `-- name: GetReviewById :one
SELECT id, product_id, user_id, rating, comment, created_at, updated_at
FROM reviews
WHERE id = $1
`

func (q *Queries) GetReviewById(ctx context.Context, id int32) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewById, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewsByProductId = `-- name: GetReviewsByProductId :many
SELECT id, product_id, user_id, rating, comment, created_at, updated_at
FROM reviews
WHERE product_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type GetReviewsByProductIdParams struct {
	ProductID sql.NullInt32 `json:"product_id"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) GetReviewsByProductId(ctx context.Context, arg GetReviewsByProductIdParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsByProductId, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, product_id, user_id, rating, comment, created_at, updated_at
FROM reviews
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListReviewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET product_id = $2, user_id = $3, rating = $4, comment = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, user_id, rating, comment, created_at, updated_at
`

type UpdateReviewParams struct {
	ID        int32          `json:"id"`
	ProductID sql.NullInt32  `json:"product_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, updateReview,
		arg.ID,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
